import React from 'react';
import Paper from '@mui/material/Paper';
import Footer from '../../components/Footer/Footer';
import styles from './TermsPage.module.css';

function TermsPage() {
  return (
    <div className={styles.container}>
      <Paper className={styles.privacyWrapper}>
        <h3>Terms of Use</h3>
        <h4>
          This document is an electronic record in terms of Information Technology Act, 2000 and
          rules there under as applicable and the amended provisions pertaining to electronic
          records in various statutes as amended by the Information Technology Act, 2000. This
          electronic record is generated by a computer system and does not require any physical or
          digital signatures. This document sets out the Terms and Conditions for renting vehicle
          from M/s Indus Motor Company Pvt. Ltd., a company incorporated under the companies
          Act.......with CIN......... This document is an agreement between M/s Indus Motor Company
          Pvt. Ltd. (herein after referred to as Indus GO) and Users (herein after referred to as
          User) and is legally binding between the User and the Indus GO . This document will be
          effective upon your acceptance of the same and will govern the relationship between User
          and Indus GO for the use of the vehicles (herein after referred to as vehicles) offered
          through website www.indusgo.in (herein after referred to as website) and through mobile
          application under the name and style of Indus GO. (herein after referred to as app) For
          the purpose of these Terms and conditions, wherever the context so require, the term : i.
          Vehicle shall mean the vehicle rented by the User from company along with all its parts
          including but not limited to, tires (including spare tire), tools, vehicle documents,
          accessories and equipment. ii. User shall mean the guest users or registered users, who
          are availing the vehicle from the company iii. Website/App shall mean the platform through
          which Indus GO services are provided Users are requested to read the Terms and condition
          of this agreement carefully before using or registering on the website/app or availing
          services through the website/app of Indus GO. If you do not agree with this Terms and
          conditions , please do not use the website/app or avail any services being offered through
          website/app Upon accepting the Terms and Conditions as set out herein after , the User
          agrees and acknowledges that : i. The terms and conditions of services provided by the
          company has displayed in the website/app. ii. User has read and understood the Terms and
          Conditions including those relating to rental of vehicles, payment structure, usage of
          vehicles, damages, cancellation, obligation of the users, Traffic violation and penalties
          so on. iii. Company reserves the right to change the terms and conditions of this
          agreement from time to time with the provision of notice in a timely manner. Notice to the
          user shall be considered served when these terms and conditions updated on the website/app
          and user viewed those changes when log on to the website, by email to the user’s
          registered email ID to the company, or through SMS to the user’s registered mobile number
          to the company. The user agrees that the amended Terms and conditions of this agreement
          shall be effective and binding on the date when such change is posted on the website or on
          the date indicated in the notice. iv. The provision of the vehicle to the user is subject
          to the acceptance of all the Terms and conditions set out here in. In the event that user
          does not accept any Terms and conditions as provided herein or as may be amended, user
          shall not be authorized to use any vehicle provided by the company. 1. Eligibility to
          enrol as Users Any person desirous of enrolling as a user with Indus GO, Users should
          possess the following eligible criteria
        </h4>
      </Paper>

      <Footer />
    </div>
  );
}

export default TermsPage;
